-- MusicPulse Phase 4 migration (004): growth/prediction/monetization tables.
-- Auto-applied at startup via Base.metadata.create_all; SQL for Postgres deploys.
CREATE TABLE IF NOT EXISTS audience_metrics (
  id SERIAL PRIMARY KEY, channel VARCHAR(64) NOT NULL, node VARCHAR(128) DEFAULT 'global',
  followers INTEGER DEFAULT 0, subscribers INTEGER DEFAULT 0, traffic INTEGER DEFAULT 0,
  conversions INTEGER DEFAULT 0, spend DOUBLE PRECISION DEFAULT 0.0,
  recorded_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS acquisition_events (
  id SERIAL PRIMARY KEY, event_type VARCHAR(64) NOT NULL, channel VARCHAR(64) DEFAULT '',
  node VARCHAR(128) DEFAULT 'global', count INTEGER DEFAULT 0,
  cost DOUBLE PRECISION DEFAULT 0.0, recorded_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS network_nodes (
  id SERIAL PRIMARY KEY, name VARCHAR(128) NOT NULL UNIQUE, kind VARCHAR(32) NOT NULL,
  parent VARCHAR(128) DEFAULT '', region VARCHAR(8) DEFAULT 'US',
  active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS owned_assets (
  id SERIAL PRIMARY KEY, name VARCHAR(128) NOT NULL UNIQUE, kind VARCHAR(32) NOT NULL,
  traffic INTEGER DEFAULT 0, revenue DOUBLE PRECISION DEFAULT 0.0,
  growth DOUBLE PRECISION DEFAULT 0.0, engagement DOUBLE PRECISION DEFAULT 0.0,
  valuation DOUBLE PRECISION DEFAULT 0.0, updated_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS trend_predictions (
  id SERIAL PRIMARY KEY, subject_type VARCHAR(32) NOT NULL, subject VARCHAR(255) NOT NULL,
  horizon_days INTEGER DEFAULT 7, confidence DOUBLE PRECISION DEFAULT 0.0,
  opportunity DOUBLE PRECISION DEFAULT 0.0, rationale TEXT DEFAULT '',
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS breakout_alerts (
  id SERIAL PRIMARY KEY, kind VARCHAR(32) NOT NULL, subject VARCHAR(255) NOT NULL,
  signal DOUBLE PRECISION DEFAULT 0.0, acknowledged BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS monetization_rules (
  id SERIAL PRIMARY KEY, name VARCHAR(128) NOT NULL UNIQUE, rule_type VARCHAR(32) NOT NULL,
  config_json TEXT DEFAULT '{}', active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS revenue_actions (
  id SERIAL PRIMARY KEY, action VARCHAR(128) NOT NULL, campaign_id INTEGER DEFAULT 0,
  amount DOUBLE PRECISION DEFAULT 0.0, status VARCHAR(32) DEFAULT 'planned',
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS product_catalog (
  id SERIAL PRIMARY KEY, name VARCHAR(128) NOT NULL UNIQUE, kind VARCHAR(32) NOT NULL,
  price DOUBLE PRECISION DEFAULT 0.0, active BOOLEAN DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS product_sales (
  id SERIAL PRIMARY KEY, product_id INTEGER NOT NULL, amount DOUBLE PRECISION DEFAULT 0.0,
  retained BOOLEAN DEFAULT TRUE, recorded_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS forecast_results (
  id SERIAL PRIMARY KEY, scope VARCHAR(32) NOT NULL, horizon VARCHAR(16) NOT NULL,
  projection_json TEXT DEFAULT '[]', risks_json TEXT DEFAULT '[]', created_at TIMESTAMP DEFAULT NOW()
);
