[alembic]
script_location = migrations
prepend_sys_path = .

[loggers]
keys = root

[handlers]
keys = console

[logger_root]
handlers = console
level = INFO

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatters]
keys = generic
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
